language: c++
sudo: required
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.7 CC=clang-3.7
      compiler: clang
      before_install:
        - if [ "$CC"  != "clang-3.7"   ]; then export CC=clang-3.7; fi
        - if [ "$CXX" != "clang++-3.7" ]; then export CXX=clang++-3.7; fi
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.8
            - g++-5
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      compiler: gcc
      before_install:
        - if [ "$CC"  != "gcc-5"     ]; then export CC=gcc-5; fi
        - if [ "$CXX" != "g++-5"     ]; then export CXX=g++-5; fi
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
cache:
  apt: true

#  - export CXXFLAGS="-std=c++14 -stdlib=libc++"

script:
  - cmake --version
  - $CC --version
  - $CXX --version
  - mkdir build
  - cd build
  - cmake .. && make

notifications:
  email: false

