# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.7

# Enable C++ support
language: cpp
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

# Run multile compilers
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
